import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Nationality } from '@prisma/client';

export class ParticipantResponseDto {
  @ApiProperty({ example: 1, description: 'Unique ID of the participant generated by the database' })
  id!: number;

  @ApiProperty({ example: 'Jakub', description: 'Participant name' })
  name!: string;

  @ApiProperty({ example: 'Luzak', description: 'Participant surname' })
  surname!: string;

  @ApiProperty({ example: '2007-10-27', description: 'Participant birth date' })
  birthDate!: Date;

  @ApiProperty({ example: 'Polish', description: 'Participant nationality' })
  nationality!: Nationality;

  @ApiProperty({ example: 'jan.luzak@gmail.com', description: 'Participant email address' })
  email!: string;
}