import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Nationality } from '@prisma/client';
import { Exclude } from 'class-transformer';

export class ParticipantResponseDto {
  @ApiProperty({ example: 1, description: 'Unique ID of the participant generated by the database' })
  id!: number;

  @ApiProperty({ example: 'Jakub', description: 'Participant name' })
  name!: string;

  @ApiProperty({ example: 'Luzak', description: 'Participant surname' })
  surname!: string;

  @Exclude()
  birthDate!: Date;

  @ApiProperty({ example: 'Polish', description: 'Participant nationality' })
  nationality!: Nationality;

  @Exclude()
  email!: string;
}