import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class TripResponseDto {
  @ApiProperty({ example: 1, description: 'Unique ID of the trip generated by the database' })
  id!: number;

  @ApiProperty({ example: 'Trip to the mountains', description: 'Trip name' })
  name!: string;

  @ApiProperty({ example: '2026-08-15', description: 'Trip start date' })
  startDate!: string;

  @ApiProperty({ example: '2026-08-27', description: 'Trip end date' })
  endDate!: Date;

  @ApiPropertyOptional({ example: 'A trip to the mountains with friends', description: 'Trip description' })
  description?: string;
}