import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Currency } from '@prisma/client';

export class ExpenseResponseDto {
  @ApiProperty({ example: 1, description: 'Unique ID of the expense generated by the database' })
  id!: number;

  @ApiProperty({ example: 1, description: 'ID of the participant associated with this expense' })
  id_participant!: number;

  @ApiProperty({ example: 1, description: 'ID of the trip associated with this expense' })
  id_trip!: number;

  @ApiProperty({ example: 100.0, description: 'Amount of the expense' })
  amount!: number;

  @ApiProperty({ example: 'EUR', description: 'Currency of the expense' })
  currency!: Currency;

  @ApiPropertyOptional({ example: '2026-08-27', description: 'Date of the expense' })
  date!: Date;
}